# -*- coding: utf-8 -*-
#
# English Language RTD & Sphinx config file
#

# General information about the project.
project = u'esp-modem'
copyright = u'2016 - 2021, Espressif Systems (Shanghai) Co., Ltd'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'en'

extensions = ['breathe', 'recommonmark']

breathe_projects = {'esp_modem': 'xml'}

breathe_default_project = 'esp_modem'

source_suffix = ['.rst', '.md']

source_parsers = {
    '.md': 'recommonmark.parser.CommonMarkParser',
}
