---
commitizen:
  bump_message: 'bump(net_connect): $current_version -> $new_version'
  pre_bump_hooks: python ../../ci/changelog.py net_connect
  tag_format: net_connect-v$version
  version: 0.0.1
  version_files:
  - idf_component.yml
