---
commitizen:
  bump_message: 'bump(console): $current_version -> $new_version'
  pre_bump_hooks: python ../../ci/changelog.py console_cmd_wifi
  tag_format: console_cmd_wifi-v$version
  version: 0.0.9
  version_files:
  - idf_component.yml
