[package]
name = "mdns"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
dns-parser = "0.8"
socket2 = "*"
nix = "0.26"
lazy_static = "*"

[build-dependencies]
cc = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
ffi = []
