#!/usr/bin/env bash

set -e

if ! git show -s | grep -q '@bot bump '; then
    echo "@bot: No bump command in the current (merge) commit, not updating..."
    exit 0;
fi

echo "Checking all components:"
for comp in asio modem websocket mdns mqtt_cxx; do
    BUMP_CMD=`git show -s | grep "@bot bump ${comp}"` || true
    if [ ! -z "${BUMP_CMD}" ]; then
        BUMP_ARGS=${BUMP_CMD##*bump ${comp} }
        echo "Bumping version number of component ${comp} (${BUMP_ARGS})"
        git config --global --add safe.directory "*"
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local pull.rebase true

        pip install commitizen sh

        cd components/${comp}
        cz bump ${BUMP_ARGS}

        CURRENT_TAG=`git describe --exact-match --tags`
        echo "CURRENT_TAG=${CURRENT_TAG}" >> "$GITHUB_ENV"

        GITHUB_DOMAIN=${GITHUB_SERVER_URL#*//}
        CURRENT_BRANCH="$(git branch --show-current)"
        REPO="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@${GITHUB_DOMAIN}/${GITHUB_REPOSITORY}.git"
        git pull "$REPO" "$CURRENT_BRANCH"
        git push "$REPO" "HEAD:${CURRENT_BRANCH}" --tags
        echo "component ${comp} updated to ${CURRENT_TAG}"
        exit 0
    fi
done
