name: Build ASIO

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        idf_ver: ["latest"]
        idf_target: ["esp32"]

    runs-on: ubuntu-20.04
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - name: Checkout esp-protocols
        uses: actions/checkout@master
        with:
          path: esp-protocols
      - name: Build ${{ matrix.example }} with IDF-${{ matrix.idf_ver }} for ${{ matrix.idf_target }}
        env:
          IDF_TARGET: ${{ matrix.idf_target }}
        shell: bash
        run: |
          . ${IDF_PATH}/export.sh
          cd $GITHUB_WORKSPACE/esp-protocols/components/asio/examples/asio_chat
          idf.py build
          cd $GITHUB_WORKSPACE/esp-protocols/components/asio/examples/async_request
          idf.py build
          cd $GITHUB_WORKSPACE/esp-protocols/components/asio/examples/socks4
          idf.py build
          cd $GITHUB_WORKSPACE/esp-protocols/components/asio/examples/ssl_client_server
          idf.py build
          cd $GITHUB_WORKSPACE/esp-protocols/components/asio/examples/tcp_echo_server
          idf.py build
          cd $GITHUB_WORKSPACE/esp-protocols/components/asio/examples/udp_echo_server
          idf.py build
