name: "6lowpan_ble: build-tests"

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  build_6lowpan_ble:
    if: contains(github.event.pull_request.labels.*.name, 'component::6lowpan_ble') || github.event_name == 'push'
    name: Build
    strategy:
      matrix:
        idf_ver: ["latest", "release-v5.2", "release-v5.3"]

    runs-on: ubuntu-22.04
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - name: Checkout esp-protocols
        uses: actions/checkout@v4
      - name: Build with IDF-${{ matrix.idf_ver }}
        shell: bash
        run: |
          . ${IDF_PATH}/export.sh
          pip install idf-component-manager idf-build-apps --upgrade
          python ci/build_apps.py components/netif_6lowpan_ble/examples/ -m components/netif_6lowpan_ble/examples/.build-test-rules.yml -c
