name: Docs and Publish Websockets

on:
  push:
    branches:
      - master

jobs:
  docs_build:
    name: Docs-Build-And-Upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout esp-protocols
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Generate docs
        run: |
          sudo apt-get update
          sudo apt-get -y install doxygen clang python3-pip git
          sudo git clone https://github.com/espressif/esp-idf
          python -m pip install breathe recommonmark
          python -m pip install -r esp-idf/docs/requirements.txt
          cd $GITHUB_WORKSPACE/components/esp_websocket_client/docs
          ./generate_docs
          mkdir -p $GITHUB_WORKSPACE/docs/esp_websocket_client
          cp -r html/. $GITHUB_WORKSPACE/docs/esp_websocket_client
          cd $GITHUB_WORKSPACE/docs
          touch .nojekyll
          echo '<a href="esp_websocket_client/index.html">esp-websocket-client</a>' >> index.html

      - name: Deploy generated docs.
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: docs
